name: Run Tests (.NET 6.0)

on: 
  pull_request:
  push:
    branches:
      - main

# Kill other jobs when we trigger this workflow by sending new commits
# to the PR.
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Restore
        run: dotnet restore SafetyFirst.sln
      - name: Build with dotnet
        run: dotnet build SafetyFirst.sln -c Release --no-restore
      - name: Test with dotnet
        run: dotnet test SafetyFirst.sln -f net6.0 -c Release --no-build
